/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloJNIWMD */

#ifndef _Included_HelloJNIWMD
#define _Included_HelloJNIWMD
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloJNIWMD
 * Method:    computeDistance
 * Signature: ([D[D[[D)D
 */
JNIEXPORT jdouble JNICALL Java_HelloJNIWMD_computeDistance
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
